### ISSUE TITLE
No longer works in latest patch

### ISSUE THREAD

**Issue by devsfan1830** [boodaah/yougotmail#1]
In the patches leading to The War Within the plugin had stopped working.

**Comment by devsfan1830** [comment]
To elaborate, it seems Blizzard is renaming function calls in the patches leading to The War Within. Several of my plugins throw errors and in many, users have identified and posted manual fixes for renamed function calls. I suspect the same has happened here. Hope you can fix this.

**Comment by boodaah3d** [comment]
Thank you for bringing this to my attention. I will be working on it to have a fix soon.

**Comment by boodaah3d** [comment]
Resolved by [61ab0dc](https://github.com/boodaah3d/yougotmail/commit/61ab0dc83c5368ae85fe85c164af348157562bd6) and release pushed to curseforge.
